### ISSUE TITLE
[iOS] Bug: Successful registration with invalid email domain

### ISSUE THREAD

**Issue by LyubomirShutilov** [HelpAPaw/FriendsInNeed#19]
Steps to reproduce:
1. Open the registration form,
2. Fill in the "Email" field with invalid data.   Test data - lyubomir.shutilov@abv.sd
3. Fill in the remaining fields.

Expected result:
Error message should appear.

Actual result:
System message for successful registration is shown.

https://user-images.githubusercontent.com/99404185/153501805-8546bc39-6b90-4649-84c8-c3fcd004e0af.mp4

**Comment by z-zafirov** [comment]
I think there is no benefit of adding an endpoint check for email domain existence. And limiting the allowed email domains for that input is not a good idea in long term too.

**Comment by BurningAXE** [comment]
Successful is only the first step of the registration. The registered user is not activated until the email is confirmed which obviously won't happen with an invalid email. Except for filling the database with some invalid users there is no significant drawback so I don't think this deserves any special attention.
