### ISSUE TITLE
[iOS] Bug: Unsuccessful registration with valid credential

### ISSUE THREAD

**Issue by LyubomirShutilov** [HelpAPaw/FriendsInNeed#20]
Steps to reproduce:

1. Open the registration form,
2. Fill in valid credential in required fields.

Expected result:
Successful message should appear.

Actual result:
Error message for existing account is shown.

Bug connected with a previous (#19) 

https://user-images.githubusercontent.com/99404185/153503787-e9564ad0-26d4-431a-9897-2afa1f1cbfbe.mp4

**Comment by LyubomirShutilov** [comment]
I have a successfully registered account with email - lyubomir.shutilov@abv.sd (#19) but that is what blocked my registration with valid email - lyubomir.shutilov@abv.bg

**Comment by z-zafirov** [comment]
I am not able to reproduce the error message with different email addresses, except when the account has been already registered via AppleID, Facebook or Google. But that can not be verified as I don't have an email neither in my inbox nor in the spam folder.

**Comment by LyubomirShutilov** [comment]
My recommendation is to try to register with the wrong domain (#19 ), because obviously the application does not recognize it, and then do the right one.

Example:
z-zafirov@abv.rt for invalid email data
z-zafirov@abv.bg for valid email data.

**Comment by BurningAXE** [comment]
The reason for the error is that there is already a registered user with email '[lyubomir.shutilov@abv.bg](mailto:lyubomir.shutilov@abv.bg)' made with a third party service (Facebook/Apple/Google). As the email is the unique identifier any other registration with the same email is rejected.
