### ISSUE TITLE
[iOS] Veterinary clinics button missing

### ISSUE THREAD

**Issue by NikKonst93** [HelpAPaw/FriendsInNeed#26]
In the iOS version of the app, this button missing from the Home page.
![Screenshot_20240705-161121~2](https://github.com/HelpAPaw/FriendsInNeed/assets/126391723/553ba992-bfad-4411-b155-f589870b01fd)
![IMG_5954](https://github.com/HelpAPaw/FriendsInNeed/assets/126391723/6feac395-2b9d-437a-8586-819f5e101193)

**Comment by BurningAXE** [comment]
Hey! Thanks for reporting. This functionality is indeed not available currently in iOS. We are in the process of rewriting the two native apps in Flutter and once done both apps will have the "Nearby clinics" feature.
